### ISSUE TITLE
Can somebody tell me what the value of main.class?

### ISSUE THREAD

**Issue by adarali** [Kotlin/kotlin-examples#135]
What's the value of main.class in this page?
https://kotlinlang.org/docs/reference/using-maven.html

**Comment by SebastianAigner** [comment]
Hi @adarali and happy 2021! Sorry the docs on this weren't clear. You are supposed to manually set `main.class` to the value of your class. When you have a file called `MyApp.kt` which contains your `main` function, you would set this value to be `MyAppKt` (for the general naming scheme, see here: https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html#package-level-functions).

Hope this helps! Feel free to reopen if the problem persists.
